%{



%}

% token
ID IF ELSE ENDIF PRINT RETURN INT FLOAT VAR FOR FROM TO CR SE LE TOI
TWO_POINTS_ASSIGNATION STRING CTE_FLOAT CTE_INT GREATER_OR_EQUAL LESS_OR_EQUAL EQUAL NOT_EQUAL

%%
prog                : asignacion